# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "202780340f92ceb076857c78337a3910"
name = "ConversionOptimizer"
application_url = "https://conversion-optimizer-api-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://conversion-optimizer-api-production.up.railway.app/api/auth/callback"
]
